### PR TITLE
added sydechapter, sydesection and sydesubsection

### PR DESCRIPTION
**Pull request by bcaldwell**
subsubsection shouldnt be numbered in the TOC so I added sydechapter, sydesection and sydesubsection.

### CODE REVIEW

**Comment by nolan-cerebras** [comment]
lgtm 👍

**Comment by LaurierMantel** [comment]
🚢 :it:

**Comment by Erik-J-D** [comment]
Good catch @benjamincaldwell 
No need to redefine chapters though, you can tell Latex to stop numbering stuff after subsections:

`\setcounter{secnumdepth}{2}`

I'll add that to the .sty and close this.

**Comment by Erik-J-D** [comment]
Fixed in cdf90b5bec3a2f963ad3fda07b47731570d6e1b2

**Pull request closed without merging**
